export enum LightEffectEnum {
    FixedOn = 1,
    Respire = 2,
    Rainbow = 3,
    FlashAway = 4,
    Raindrops = 5,
    RainbowWheel = 6,
    RippleShining = 7,
    StarsTwinkle = 8,
    RetroSnake = 9,
    NeonStream = 10,
    Reaction = 11,
    SineWave = 12,
    RotatingWindmill = 13,
    ColorfulWaterfall = 14,
    Blossoming = 15,
    SelfDefine = 19,
    OFF = 0,
    Music = 20
}